name: check

permissions:
  actions: read
  contents: read
  security-events: write
  checks: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 34 8 * * 0

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: install-ruby
        uses: ruby/setup-ruby@v1.235.0
        with:
          ruby-version: 3.4.2
      - name: install-dependencies
        run: bundle install
      - name: check
        uses: trunk-io/trunk-action@v1.1.19
  devskim:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: check
        uses: microsoft/DevSkim-Action@v1.0.15
      - name: upload
        uses: github/codeql-action/upload-sarif@v3.28.16
        with:
          sarif_file: devskim-results.sarif
  osv:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.1
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  osv-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.0.1
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
